Repository FortunaSS13/Fortuna, pull requests merged in 2021-12, with the labels that each got.

#474 Sprite Fix/Clothing Update
  code/modules/clothing/head/f13factionhead.dm
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Bugfix, Testmerge Candidate

#466 buffs some gunsi got asked to
  code/modules/projectiles/projectile/beams.dm
Labels: stale

#472 Drugs and powercells
  _maps/map_files/DR2sPrefabs.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/Pahrump/old/Dungeons.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  _maps/map_files/templates/dungeons/north_bunker_1.dmm
  _maps/map_files/templates/dungeons/oasis_bunker_1.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/f13storage.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/modules/WVM/wmv_buyer.dm
  code/modules/WVM/wvm.dm
  code/modules/fallout/obj/items.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/power/cell.dm
  code/modules/reagents/reagent_containers/bottle.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/uplink/uplink_items/uplink_devices.dm
  icons/fallout/objects/medicine/chemical.dmi
  icons/fallout/objects/medicine/drugs.dmi
  icons/fallout/objects/medicine/syringe.dmi
  icons/fallout/objects/powercells.dmi
  icons/fallout/objects/storage.dmi
  icons/obj/chemical.dmi
  icons/obj/power.dmi
  icons/obj/syringe.dmi
  testing.dmm
Labels: Sprites

#471 event coordinator panel, fullscreen, various
  code/__DEFINES/vv.dm
  code/datums/datumvars.dm
  code/game/objects/items/plushes.dm
  code/modules/admin/topic.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/client/client_defines.dm
  code/modules/vending/wardrobes.dm
  fallout/misc/staffchat.dm
Labels: UI

#456 Removes ranger speedup
  code/modules/clothing/suits/f13factionarmor.dm
Labels: stale-exempt, Testmerge Candidate
