Repository FortunaSS13/Fortuna, pull requests merged in 2021-11, with the labels that each got.

#403 Mob rebalance I: Ghouls and Wastebots
  code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
Labels: Balancing, Currently Testmerged

#405 Admin Launch Pod Bays
  _maps/map_files/generic/CentCom.dmm
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
Labels: ⭐ maintainer's gold star, Testmerge Candidate

#404 experimental hitscan aer9 but the pr works
  code/modules/projectiles/ammunition/caseless/misc.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/ammunition/energy/special.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Currently Testmerged

#410 did you know we had pulse grenade noises w enever used
  code/game/objects/items/grenades/emgrenade.dm
Labels: Currently Testmerged

#400 adds fermichem stimpaks
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/game/objects/items/storage/f13storage.dm
  code/modules/fallout/reagents/medicines.dm
  code/modules/food_and_drinks/food/snacks_cake.dm
  code/modules/food_and_drinks/food/snacks_frozen.dm
  code/modules/food_and_drinks/food/snacks_pie.dm
  code/modules/food_and_drinks/food/snacks_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_bread.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_frozen.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/hydroponics/grown/broc.dm
  code/modules/hydroponics/grown/xander.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/impure_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balancing, Bugfix, ⭐ maintainer's gold star, Adjustment, Content, Currently Testmerged

#427 Khan loadouts
  code/modules/jobs/job_types/wasteland.dm
Labels: Balancing, Currently Testmerged

#393 improves raider outlaw loadouts a bit and adds a few new ones
  code/modules/clothing/suits/light_armor.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balancing

#409 constructicons, combine to form new ways to make things
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/turfs/simulated/floor/plating.dm
Labels: Content, Currently Testmerged

#417 disables mutation toxins
  code/modules/fallout/obj/structures/barrel.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/research/xenobiology/crossbreeding/regenerative.dm
Labels: Currently Testmerged

#433 webedit service
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balancing

#425 ui changes
  code/datums/browser.dm
  code/modules/mob/dead/new_player/new_player.dm
  html/browser/common.css
Labels: Currently Testmerged, Awaiting Host Approval

#428 Adjusts respawn timer
  code/__DEFINES/mobs.dm
Labels: Currently Testmerged

#440 Homemade flagpoles
  code/game/objects/items/stacks/rods.dm
Labels: Currently Testmerged

#438 Quick raider combat armor nerf
  code/modules/clothing/suits/f13armor.dm
Labels: Currently Testmerged

#442 Follower flag creation
  code/game/objects/items/fallout13misc.dm
Labels: Currently Testmerged

#447 Goodbye spiders, hello Mirelurks.
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Map, Testmerge Candidate

#429 Grey and brown robes
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged

#437 hitscan lasers in
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Currently Testmerged

#434 we want you to join the mob!
  code/modules/jobs/job_types/wasteland.dm
  code/modules/jobs/jobs.dm
Labels: stale, Testmerge Candidate

#424 Fixes up salvaging a bit, adds new blueprints
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/granters.dm
  code/game/objects/structures/wrecks.dm
  code/modules/crafting/items.dm
Labels: Currently Testmerged

#443 Furniture and other Mapping assets
  _maps/map_files/Pahrump/old/Pahrump.dmm
  code/__DEFINES/footsteps.dm
  code/game/machinery/deployable.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/beds_chairs/chair.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/dresser.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/guncase.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/fallout/obj/campfire.dm
  code/modules/fallout/obj/structures/obstacle.dm
  code/modules/fallout/turf/ground.dm
  code/modules/hydroponics/grown/towercap.dm
  code/modules/library/lib_items.dm
  code/modules/mining/lavaland/ruins/gym.dm
  goon/icons/obj/fitness.dmi
  icons/fallout/objects/furniture/chairs_and_beds.dmi
  icons/fallout/objects/furniture/closet.dmi
  icons/fallout/objects/furniture/heating.dmi
  icons/fallout/objects/furniture/junk.dmi
  icons/fallout/objects/furniture/stationary.dmi
  icons/fallout/objects/structures/stationary.dmi
  icons/fallout/structures/barricades.dmi
  icons/fallout/structures/fences.dmi
  icons/fallout/turfs/gravel.dmi
  icons/fallout/turfs/wasteland.dmi
  icons/obj/chairs.dmi
  icons/obj/fence.dmi
  icons/obj/hydroponics/equipment.dmi
  icons/obj/objects.dmi
  icons/obj/stationobjs.dmi
  sound/effects/footstep/gravel1.ogg
  sound/effects/footstep/gravel2.ogg
  sound/effects/footstep/gravel3.ogg
  sound/effects/footstep/gravel4.ogg
  sound/effects/footstep/hull1.ogg
  sound/effects/footstep/hull2.ogg
  sound/effects/footstep/hull3.ogg
  sound/effects/footstep/hull4.ogg
  sound/effects/footstep/hull5.ogg
  sound/effects/footstep/sand1.ogg
  sound/effects/footstep/sand2.ogg
  sound/effects/footstep/sand3.ogg
  sound/effects/footstep/sand4.ogg
  sound/effects/footstep/snow1.ogg
  sound/effects/footstep/snow2.ogg
  sound/effects/footstep/snow3.ogg
  sound/effects/footstep/snow4.ogg
  sound/effects/footstep/snow5.ogg
Labels: ⭐ maintainer's gold star, Currently Testmerged

#421 adds some preliminary ammo types for testing
  code/game/machinery/autolathe.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/ammunition/ballistic/sniper.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/projectiles/projectile/bullets/smg.dm
  code/modules/projectiles/projectile/bullets/sniper.dm
  code/modules/research/designs/ammolathe_designs.dm
  fortune13.dme
Labels: Currently Testmerged

#455 legion speedboost removal
  code/modules/clothing/suits/f13factionarmor.dm
Labels: Testmerge Candidate

#390 asay, staffchat, and rights adjustments
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminsay.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/client/client_procs.dm
  fallout/misc/staffchat.dm
  fortune13.dme
  modular_citadel/code/modules/client/client_procs.dm
Labels: Testmerge Candidate

#458 mostly viewport things
  code/controllers/configuration/entries/general.dm
  code/datums/view.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/player_details.dm
  code/modules/mob/login.dm
  fortune13.dme
  icons/blank_title.png
  interface/skin.dmf
Labels: Testmerge Candidate

#454 Open Door Policy
  _maps/RandomZLevels/away_mission/wildwest.dmm
  _maps/map_files/DR2sPrefabs.dmm
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/Pahrump/old/Pahrump.dmm
  _maps/map_files/templates/dungeons/north_sewer_2.dmm
  _maps/map_files/waste.dmm
  _maps/templates/small_shuttle_1.dmm
  code/game/machinery/doors/city_gate.dm
  code/game/machinery/doors/unpowered.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/timeddoor.dm
  code/modules/fallout/obj/structures/simple_door.dm
  icons/fallout/objects/furniture/chairs_and_beds.dmi
  icons/fallout/objects/furniture/junk.dmi
  icons/fallout/objects/structures/campfire.dmi
  icons/fallout/objects/structures/doors.dmi
  icons/fallout/objects/structures/furniture.dmi
  icons/fallout/structures/brotherhood_gate.dmi
  icons/fallout/structures/city_gate.dmi
  icons/fallout/structures/doors.dmi
  icons/fallout/turfs/doors.dmi
  icons/obj/doors/wasteland_doors.dmi
  icons/obj/doors/wastelanddoors.dmi
  testing.dmm
Labels: DNM: Conflicts, ⭐ maintainer's gold star, Testmerge Candidate
