Repository FortunaSS13/Fortuna, pull requests merged in 2021-09, with the labels that each got.

#77 Removes some NCR Helmets
  code/modules/jobs/job_types/ncr.dm
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Removal

#76 Armor Durability Removal
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/f13armor.dm
Labels: DNM, Removal

#89 Add a few BoS off-duty slots
  code/modules/jobs/job_types/bos.dm
Labels: Adjustment

#88 Removes the capes from the BoS paladins, replaces with shoulder holsters.
  code/modules/jobs/job_types/bos.dm
Labels: Adjustment

#92 Changes stale workflow labels
  .github/workflows/stale.yml
Labels: ⚙ Workflows

#58 Adds cosmetic stealth suit
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/under/f13.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/clothing_lefthand.dmi
  icons/mob/inhands/clothing_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites, Content

#93 BoS feedback tweaks
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Map, Adjustment

#96 Quick BoS fix
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Map, Adjustment

#97 Fixes broken-ass icons on cosmetic stealth suit
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Bugfix, Sprites

#86 Disables the spread on glowshrooms
  code/game/objects/effects/glowshroom.dm
Labels: Removal

#95 Raider change
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  icons/mob/wastemobs.dmi
Labels: Bugfix, Adjustment

#99 Brotherhood of Steel changes
  code/modules/jobs/job_types/bos.dm
  code/modules/projectiles/guns/energy/laser.dm
Labels: Adjustment, Content

#100 Move Enclave bunker to VR Z-level
  _maps/RandomZLevels/VR/yuma_VR.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/game/area/areas/away_content.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/clothing/outfits/vr.dm
  config/vr_config.txt
Labels: Balancing, Map, Removal, ⚠ Config

#114 Complete and fix the alien blaster
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/storage/concrete/pockets.dm
  code/game/machinery/cell_charger.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/game/objects/items/storage/belt.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammunition/energy/plasma.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: Bugfix

#90 Removes closet looking for ghosts
  code/game/objects/structures/crates_lockers/closets.dm
Labels: ⚠ Admin Tools, Adjustment

#107 Replaces the den's (four shade suit) with a special and themed (has gold on it) suit.
  code/modules/clothing/under/f13.dm
  code/modules/jobs/job_types/wasteland.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Adjustment

#109 Add Reinforced Rider Helmet
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/modules/clothing/head/f13head.dm
  icons/fallout/clothing/hats.dmi
  icons/fallout/onmob/clothes/head.dmi
Labels: Sprites, Content

#79 Update automatic.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balancing

#125 Brotherhood Loadout Adjustments
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  _maps/map_files/templates/dungeons/north_bunker_1.dmm
  _maps/map_files/templates/dungeons/north_sewer_1.dmm
  _maps/map_files/templates/dungeons/oasis_bunker_2.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/effects/spawners/themed_loot_tables.dm
  code/game/objects/items/storage/survivalkit.dm
  code/modules/crafting/items.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/ammunition/caseless/misc.dm
  code/modules/projectiles/ammunition/energy/laser.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/research/designs/ammolathe_designs.dm
  icons/fallout/objects/guns/ballistic.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/inhands/weapons/guns_lefthand.dmi
  icons/mob/inhands/weapons/guns_righthand.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/guns/projectile.dmi
Labels: Balancing

#122 Upgrade lighting sybsystem
  code/controllers/subsystem/lighting.dm
Labels: Bugfix

#119 The big VR Update
  _maps/RandomZLevels/VR/yuma_VR.dmm
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/area/areas/away_content.dm
  code/game/area/areas/holodeck.dm
  code/game/machinery/computer/teleporter.dm
  code/game/objects/items/circuitboards/machine_circuitboards.dm
  code/game/objects/items/devices/beacon.dm
  code/modules/VR/vr_sleeper.dm
  code/modules/clothing/outfits/vr.dm
  code/modules/holodeck/computer.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/followers.dm
  code/modules/jobs/job_types/wasteland.dm
  config/game_options.txt
  config/vr_config.txt
  tgui/packages/tgui/interfaces/Holodeck.js
  tgui/public/tgui.bundle.js
Labels: Map, Content

#133 Fix rebuilding TGUI on master branch
  .github/workflows/autobuild_tgui.yml
Labels: Bugfix, ⚙ Workflows

#140 Some minor fixes and tweaks to the BoS bunker.
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Bugfix, Map

#113 legion loadout changes
  code/modules/jobs/job_types/legion.dm
Labels: Balancing, Adjustment

#137 Organ Selling (complete and ready)
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/modules/WVM/wmv_buyer.dm
  code/modules/cargo/packs/organic.dm
  code/modules/hydroponics/grown/misc.dm
  code/modules/hydroponics/grown/replicapod.dm
  code/modules/hydroponics/hydroponics.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/vending/megaseed.dm
  icons/WVM/machines.dmi
Labels: DNM: Draft, Content

#151 Removes EXPERIMENTOR from R&D
  code/modules/research/designs/machine_designs.dm
  code/modules/research/designs/machine_desings/machine_designs_sci.dm
  code/modules/research/techweb/_techweb_node.dm
Labels: Removal

#158 a lowered cap (ha!) on trash pile loot
  code/_globalvars/lists/maintenance_loot.dm
Labels: Balancing

#139 yuma garbage day! trash piles more trash-y
  code/_globalvars/lists/maintenance_loot.dm
Labels: Balancing, Adjustment

#168 Bear vest 2 electric boogaloo
  code/modules/clothing/under/f13.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/donor.dm
Labels: Bugfix, Adjustment

#172 Pens and Paperwork 3e: Hoard of the Secretary Queen
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/storage/briefcase.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/jobs.dm
Labels: Content

#160 Adds NCR rep
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/cards_ids.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/jobs.dm
Labels: Content

#81 Updates progressbars
  code/datums/progressbar.dm
Labels: DNM, stale-exempt, Adjustment

#177 Fixes a few mapping mistakes in the Den's shop
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Map

#138 Bugfixing and Lore-friendliness
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/modules/clothing/head/f13head.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  icons/fallout/clothing/hats.dmi
  icons/obj/clothing/hats.dmi
Labels: Bugfix, Adjustment

#192 Ports Closet Storage Fix from Desert Rose (#879)
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Bugfix

#189 Peacekeeper Fix
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: Balancing, Bugfix

#174 sheriff alt-loadout improved, bluecurity is back
  code/datums/components/storage/concrete/pockets.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
Labels: Balancing

#190 NCR Rep stuff
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Content

#244 spelling checks and balances
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Balancing, Grammar
