Repository FortunaSS13/Fortuna, pull requests merged in 2021-10, with the labels that each got.

#269 webedit stimpaks into freezers and vr workbenches also mob spawners
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/datums/components/material_container.dm
  code/game/objects/effects/effect_system/effect_system.dm
  code/modules/fallout/obj/structures/mob_spawners.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/shuttle/on_move.dm
  icons/mob/nest_new.dmi
Labels: Adjustment

#270 pretty water and various fixes
  code/game/machinery/computer/arcade/battle.dm
  code/game/machinery/computer/arcade/minesweeper.dm
  code/game/machinery/computer/arcade/misc_arcade.dm
  code/game/machinery/computer/arcade/orion_trail.dm
  code/game/turfs/open.dm
  code/game/turfs/simulated/water.dm
  code/modules/fallout/turf/ground.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  icons/effects/effects.dmi
Labels: Sprites, Map, Adjustment

#242 Two MP slots
  code/modules/jobs/job_types/ncr.dm
Labels: Adjustment

#250 The Great Ammo Purge
  _maps/map_files/Pahrump/Dungeons.dmm
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  code/_globalvars/lists/maintenance_loot.dm
  code/datums/components/storage/concrete/pockets.dm
  code/game/objects/items/storage/belt.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/ammunition/ballistic/pistol.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/ammunition/ballistic/smg.dm
  code/modules/projectiles/ammunition/ballistic/sniper.dm
  code/modules/projectiles/ammunition/caseless/_caseless.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/research/designs/ammolathe_designs.dm
Labels: Removal
