Repository FortunaSS13/Fortuna, pull requests merged in 2021-08, with the labels that each got.

#15 Changes the discord link
  code/game/world.dm
Labels: ✔ Approved, Misc/Info

#12 Fixes some SQL errors
  code/modules/mob/dead/new_player/new_player.dm
Labels: ⚠ Database

#9 Changes Jet's recipe to milk instead of soy milk.
  code/datums/components/crafting/recipes/recipes_medicine.dm
Labels: ✔ Approved, Adjustment

#11 Oasis revitalization plan 1
  code/modules/jobs/job_types/oasis.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: ✔ Approved, Adjustment

#17 Table Sprites
  icons/obj/smooth_structures/reinforced_table.dmi
  icons/obj/smooth_structures/rollingtable.dmi
Labels: Sprites

#18 flashlight update
  icons/mob/inhands/misc/devices_lefthand.dmi
  icons/mob/inhands/misc/devices_righthand.dmi
  icons/obj/lighting.dmi
Labels: Sprites

#5 Removes Tinkering
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
  code/__DEFINES/traits.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/traits/good.dm
  code/game/objects/items/granters.dm
  code/game/objects/items/melee/f13powerfist.dm
  code/modules/WVM/wvm.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/crafting/items.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/flamethrower.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/hoboguns.dm
Labels: Removal

#21 Fixes legion armor sprites
  code/modules/clothing/suits/f13factionarmor.dm
  icons/fallout/clothing/armored_medium.dmi
  icons/fallout/onmob/clothes/armor_medium.dmi
Labels: Bugfix, Sprites

#34 Fixed rolebans
  code/modules/admin/topic.dm
Labels: ⚠ Admin Tools, Bugfix

#33 Long awaited powerarmor speechspan fix
  code/modules/clothing/head/_head.dm
Labels: Bugfix

#14 [MDB IGNORE] Oasis Remake (done btw)
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Map

#30 DR Sprite Port: Ranger Cloaks
  icons/mob/clothing/suit.dmi
Labels: Sprites

#31 Replaces wheelchair
  icons/obj/vehicles.dmi
Labels: Sprites

#4 pa ADJUSTED, donator GONE, tribals CRYING, vore rebase INCOMING
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/f13armor.dm
  code/modules/clothing/suits/f13factionarmor.dm
  modular_citadel/code/modules/client/loadout/__donator.dm
  modular_citadel/code/modules/client/loadout/kits.dm
Labels: Balancing, Removal

#29 [LOOTDROP BALANCING]
  code/game/objects/effects/spawners/f13lootdrop.dm
Labels: Balancing

#13 Oasis revitalization plan 1b: a rifle by your side
  code/modules/jobs/job_types/oasis.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: Balancing

#39 anti-prohibition, we need more drinks
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/vending/boozeomat.dm
  code/modules/vending/sustenance.dm
Labels: Balancing

#60 OPD missing shipment found: oops, sheriff gear was left under the couch
  code/modules/jobs/job_types/oasis.dm
Labels: Bugfix

#63 Gives followers town radio access
  code/game/objects/items/devices/radio/headset.dm
  code/modules/jobs/job_types/followers.dm
Labels: Adjustment

#67 Pool PR
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
Labels: Map, Content

#56 Fixes href log TGUI spam and removes unused files
  code/modules/client/asset_cache.dm
  code/modules/client/client_procs.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/goonchat/browserassets/css/font-awesome.css
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/goonchat/browserassets/js/errorHandler.js
  code/modules/goonchat/browserassets/js/jquery.min.js
  code/modules/goonchat/browserassets/js/json2.min.js
  code/modules/goonchat/jsErrorHandler.dm
  html/IRV/jquery-ui.custom-core-widgit-mouse-sortable-min.js
Labels: Bugfix

#70 Bugfix for diary and removal of PA book from vendors.
  code/game/objects/items/granters.dm
  code/modules/WVM/wvm.dm
Labels: Bugfix, Removal

#83 New/old but revamped BoS bunker.
  _maps/map_files/Pahrump/Pahrump-Surface-2.dmm
  _maps/map_files/Pahrump/Pahrump-Underground-1.dmm
Labels: Map
